"""empty message

Revision ID: 13581895d07e
Revises: d9f400fb9bfa
Create Date: 2017-06-03 12:25:25.303822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13581895d07e'
down_revision = 'd9f400fb9bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['search_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_counter')
    # ### end Alembic commands ###
